language: rust

cache: cargo

rust:
  - stable
  - nightly

os:
  - linux
  - osx

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

install:
  - ./scripts/install-alsa.sh

script:
  - cargo build
  - cargo test
