sudo: required

before_cache:
- rm -rf /home/travis/.cargo/registry

cache:
  directories:
  - /home/travis/.cargo

git:
  depth: 5

addons:
  apt:
    packages:
      - libasound2-dev

matrix:
  include:
    # Linux
    - os: linux
      language: rust
      rust: stable
      env: PACKAGE_NAME="hinterland-$TRAVIS_OS_NAME.tar.gz"
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
        - cargo test
        - cargo build --release
      before_deploy: ci/build_artifact.sh

    # OSX
    - os: osx
      language: rust
      rust: stable
      env:
        - TARGET=x86_64-apple-darwin
        - PACKAGE_NAME="hinterland-$TRAVIS_OS_NAME.tar.gz"
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
        - cargo test
        - cargo build --release
      before_deploy: ci/build_artifact.sh

    # Windows
    - os: windows
      language: rust
      rust: stable
      env:
        - TARGET=x86_64-pc-windows-msvc
        - PACKAGE_NAME="hinterland-$TRAVIS_OS_NAME.zip"
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
        - cargo test
        - cargo build --release
      before_deploy:
        - powershell -executionpolicy bypass -File "ci\build_artifact.ps1"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: p7m7Fe9rquO/GcLtbp+vu1HWUG+HxFr0DwBdfW96e/P8RAMH+R0u8QcNjb9n8/tH5K5XZcj2gMAthBjKSASNoXDiJ96ukru2m8hKugXt9QWirhwTJKFj1UUhQeSPFeK9aS99zwgnulYjdfEbWA7IomfH79GF9AKQMx78/fh9SLMz2C5SdfGSE6RXgw8/ASE4yef9UOO6ttCs2Vb3mUEw/mM/aZmGGZ49GCd4qBT2gHjzdXPXgCt18+Cqt/S/aYQia90AEHlK2DUX2w/IauPmNNOu4xqwijz8HXBfyBPxZerRBS0yVqUiMkNRYfLLdFgaWWGnjcOPUpHQMOLTDXO1LfLV0zNSAZPU8MT8cm9lFDJgCZWMYA+h+wxkFQgT6NSH0M/avjwkCpK1NLfhEcX79xKZ/Nv6FhZ+ZjeauVkNIeYL4v4SWteFfzMoCV0+oCmyYnyf1925p7MS5+qKpHUj6pBkJeS0Br17RyFLhGzFYht+5ejz1aStguHqcliYpioKikOa1WV0X+p9VpBH1RMWSCG/DpmZgtveX8kck8O4YKHHs7RYfH7k61TWh503f45Y51N7KlizgCUGmdQWz0ju7jU0e8yr7PZmiAPSYWX82t1D3a53atvethhOAMYc4+LbvPiT8TuHw/rrTEd7RUL41YfzN/KK9IyklhNQEDlE51I=
  file: "$PACKAGE_NAME"
  on:
    tags: true
    repo: Laastine/hinterland
