version: 0.2.0-{build}

environment:
  RUST_BACKTRACE: full
  global:
    PROJECT_NAME: hinterland
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
  - channel: nightly

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - set PATH=C:\msys64\mingw32\bin;%PATH%
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;%PATH%
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe --default-host %TARGET% --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv

build: false

test_script:
  - cmd: 'cargo build --release'

cache:
  - target
  - C:\Users\appveyor\.cargo

before_deploy:
  - mkdir hinterland
  - mkdir hinterland\assets
  - xcopy assets\*.png hinterland\assets /y /m
  - xcopy assets\*.json hinterland\assets /y /m
  - xcopy assets\maps hinterland\assets\maps /e /i /y /s
  - xcopy assets\audio hinterland\assets\audio /e /i /y /s
  - xcopy target\release\hinterland_bin.exe hinterland\hinterland.exe*
  - 7z a ./%PROJECT_NAME%-%TARGET%.zip hinterland
  - appveyor PushArtifact ./%PROJECT_NAME%-%TARGET%.zip

deploy:
  provider: GitHub
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  force_update: true
  auth_token:
    secure: zjp/gY3ooTtDDpz3Kzi97tLidzfDIPUelcgWhb/mpt3NoSQCkLxWbXx0ujvio45F
  on:
    appveyor_repo_tag: true
