version: 0.3.11-{build}

clone_depth: 5

branches:
  only:
    - master

environment:
  RUST_BACKTRACE: full
  global:
    PROJECT_NAME: hinterland
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu

matrix:
  allow_failures:
  - channel: nightly

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - set PATH=C:\msys64\mingw32\bin;%PATH%
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;%PATH%
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe --default-host %TARGET% --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv

build: false

test_script:
  - cmd: 'cargo build --release'

cache:
  - target
  - C:\Users\appveyor\.cargo

before_deploy:
  - mkdir hinterland
  - mkdir hinterland\assets
  - xcopy assets\*.png hinterland\assets /y /m
  - xcopy assets\*.json hinterland\assets /y /m
  - xcopy assets\maps hinterland\assets\maps /e /i /y /s
  - xcopy assets\audio hinterland\assets\audio /e /i /y /s
  - xcopy target\release\hinterland.exe hinterland\hinterland.exe*
  - 7z a ./%PROJECT_NAME%-%TARGET%.zip hinterland
  - appveyor PushArtifact ./%PROJECT_NAME%-%TARGET%.zip
  - Remove-Item ./%PROJECT_NAME%-%TARGET%.zip -Force
  - Remove-Item ./hinterland/*.* -Force

deploy:
  provider: GitHub
  description: 'Windows release'
  artifact: /.*\.zip/
  force_update: true
  auth_token:
    secure: zjp/gY3ooTtDDpz3Kzi97tLidzfDIPUelcgWhb/mpt3NoSQCkLxWbXx0ujvio45F
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: "true"
