[package]
name = "hacknslash"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies.sdl2]
sdl2 = "0.27"
default-features = false
features = ["image","gfx","mixer"]

[dependencies]
chrono = "0.2.25"
conv = "0.3.3"
json = "0.11.0"
