[package]
name = "hinterland"
version = "0.3.5"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[[bin]]
name = "hinterland_bin"
path = "src/main.rs"

[dependencies]
cgmath = "0.16.1"
crossbeam-channel = "0.2.1"
gfx_core = "0.8.2"
gfx_device_gl = "0.15.2"
gfx_window_glutin = "0.23.0"
gfx = "0.17.1"
glutin = "0.15.0"
genmesh = "0.5.0"
image = "0.19.0"
json = "0.11.13"
pathfinding = "0.8.0"
rand = "0.5.3"
rodio = "0.8.0"
rusttype = "0.6.2"
specs = "0.12.0"
tiled = "0.8.0"

[features]
windowed = []
framerate = []
