[package]
name = "zombie-shooter"
version = "0.2.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies]
conv = "0.3.3"
json = "0.11.9"
tiled = "0.7.0"
cgmath = "0.15"
gfx = "0.16.1"
gfx_device_gl = "0.14.1"
gfx_window_glutin = "0.17.0"
glutin = "0.9.1"
genmesh = "0.5.0"
image = "0.15.0"
rand = "0.3.15"
specs = "0.8.1"

[features]
dev = []
