[package]
name = "hacknslash"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies.sdl2]
version = "0.29.0"
default-features = false
features = ["ttf","image","gfx","mixer"]

[dependencies]
conv = "0.3.3"
json = "0.11.5"
tiled = "0.3.0"
