[package]
name = "zombie-shooter"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies.sdl2]
version = "0.29.0"
default-features = false
features = ["ttf","image","gfx","mixer"]

[dependencies]
conv = "0.3.3"
json = "0.11.5"
tiled = "0.3.0"
cgmath = "0.7"
gfx = "0.14"
gfx_app = "0.4.0"
gfx_window_glutin = "0.14"
genmesh = "0.4"
glutin = "0.7.1"
image = "0.12.3"
noise = "0.1"
rand = "0.3"
winit = "0.5.1"
