[package]
name = "zombie_shooter"
version = "0.2.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[lib]
name = "zombie_shooter_lib"
path = "src/lib.rs"

[[bin]]
name = "zombie_shooter_bin"
path = "src/main.rs"

[dependencies]
cgmath = "0.16.0"
gfx = "0.16.3"
gfx_device_gl = "0.14.6"
gfx_window_glutin = "0.17.0"
glutin = "0.9.1"
genmesh = "0.5.0"
image = "0.18.0"
json = "0.11.12"
rand = "0.4"
rodio = "0.5.2"
specs = "0.10.0"
tiled = "0.7.2"

[features]
windowed = []
fps = []
