[package]
name = "hinterland"
version = "0.3.9"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies]
cgmath = "0.16.1"
crossbeam-channel = "0.3.3"
gfx_core = "0.8.3"
gfx_device_gl = "0.15.3"
gfx = "0.17.1"
glutin = "0.19.0"
genmesh = "0.5.0"
image = "0.20.1"
json = "0.11.13"
num = "0.2.0"
pathfinding = "1.1.2"
rand = "0.6.1"
rodio = "0.8.1"
rusttype = "0.7.3"
specs = "0.14.1"
tiled = "0.8.0"

[features]
godmode = []
framerate = []
windowed = []
