[package]
name = "zombie-shooter"
version = "0.2.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies]
conv = "0.3.3"
json = "0.11.5"
tiled = "0.5.0"
cgmath = "0.7.0"
gfx = "0.14.0"
gfx_app = "0.4.0"
gfx_window_glutin = "0.14.0"
genmesh = "0.4.0"
glutin = "0.7.1"
image = "0.12.3"
noise = "0.1.0"
rand = "0.3.0"
winit = "0.5.11"
