[package]
name = "hacknslash"
version = "0.1.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies]
sdl2 = "0.22.0"
sdl2_image = "0.22.0"
chrono = "0.2.25"
conv = "0.3.3"
json = "0.11.0"
