[package]
name = "hinterland"
version = "0.2.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[lib]
name = "hinterland_lib"
path = "src/lib.rs"

[[bin]]
name = "hinterland_bin"
path = "src/main.rs"

[dependencies]
cgmath = "0.16.1"
gfx_core = "0.8.2"
gfx_device_gl = "0.15.2"
gfx_window_glutin = "0.21.0"
gfx = "0.17.1"
glutin = "0.13.1"
genmesh = "0.5.0"
image = "0.19.0"
json = "0.11.13"
rand = "0.5.0-pre.1"
rodio = "0.7.0"
rusttype = "0.5.2"
specs = "0.11.0-alpha6"
tiled = "0.7.4"

[features]
windowed = []
fps = []
