[package]
name = "hinterland"
version = "0.3.8"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[[bin]]
name = "hinterland"
path = "src/main.rs"

[dependencies]
cgmath = "0.16.1"
crossbeam-channel = "0.2.4"
gfx_core = "0.8.2"
gfx_device_gl = "0.15.3"
gfx_window_glutin = "0.23.0"
gfx = "0.17.1"
glutin = "0.15.0"
genmesh = "0.5.0"
image = "0.19.0"
json = "0.11.13"
pathfinding = "0.8.1"
rand = "0.5.5"
rodio = "0.8.0"
rusttype = "0.7.1"
specs = "0.12.2"
tiled = "0.8.0"

[features]
godmode = []
framerate = []
windowed = []
