[package]
name = "hinterland"
version = "0.3.9"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[[bin]]
name = "hinterland"
path = "src/main.rs"

[dependencies]
cgmath = "0.16.1"
crossbeam-channel = "0.2.6"
gfx_core = "0.8.3"
gfx_device_gl = "0.15.3"
gfx_window_glutin = "0.26.0"
gfx = "0.17.1"
glutin = "0.18.0"
genmesh = "0.5.0"
image = "0.20.0"
json = "0.11.13"
pathfinding = "1.0.3"
rand = "0.5.5"
rodio = "0.8.1"
rusttype = "0.7.2"
specs = "0.14.0"
tiled = "0.8.0"

[features]
godmode = []
framerate = []
windowed = []
