[package]
name = "hinterland"
version = "0.3.9"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]
edition = "2018"

[dependencies]
winit = "0.19.0"

[features]
godmode = []
framerate = []
windowed = []
