[package]
name = "zombie-shooter"
version = "0.2.0"
authors = ["Mikko Kaistinen <mikko.kaistinen@kapsi.fi>"]

[dependencies]
conv = "0.3.3"
json = "0.11.5"
tiled = "0.5.0"
cgmath = "0.9.1"
gfx = "0.16.0"
gfx_window_glutin = "0.16.0"
gfx_device_gl = "0.14.0"
glutin = "0.8.0"
genmesh = "0.4.0"
image = "0.12.3"
noise = "0.1.0"
rand = "0.3.0"
specs = "0.8"
winit = "0.6.0"
